name: "✨ Feature request"
description: 新機能の提案
labels: ["feature"]
body:
  - type: input
    id: goal
    attributes: { label: 目的(Goal), placeholder: 何を達成したい？ }
    validations: { required: true }
  - type: textarea
    id: scope
    attributes: { label: スコープ, description: やること（箇条書き） }
  - type: textarea
    id: outofscope
    attributes: { label: スコープ外, description: やらないこと（明確に） }
  - type: textarea
    id: done
    attributes: { label: 完了条件(DoD), description: 動作確認・テスト・UIなど }
    
